version: "3"
services:
  sandbox:
    image: react-test:latest
    ports: 
      - "8080:80"
    environment:
      APP_ENV: sandbox
  production:
    image: react-test:latest
    ports: 
      - "8081:80"
    environment:
      APP_ENV: production